---
- name: Enable remi repo for PHP 8.0.
  set_fact: php_enablerepo="remi,remi-php80"
  when: php_version == "8.0"

- name: Enable remi repo for PHP 8.1.
  set_fact: php_enablerepo="remi,remi-php81"
  when: php_version == "8.1"

- name: Enable remi repo for PHP 8.2.
  set_fact: php_enablerepo="remi,remi-php82"
  when: php_version == "8.2"

- name: Enable remi repo for PHP 8.3.
  set_fact: php_enablerepo="remi,remi-php83"
  when: php_version == "8.3"

# See: https://github.com/ansible/ansible/issues/64852
- block:

    - name: Ensure dnf-plugins are installed on CentOS 8+.
      yum:
        name: dnf-plugins-core
        state: present

    - name: Enable crb and DNF module for CentOS 8+.
      shell: |
        dnf config-manager --set-enabled crb
        dnf module enable -y php:remi-{{ php_version }}
      register: dnf_module_enable
      changed_when: "'Nothing to do' not in dnf_module_enable.stdout"

  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8
